#!/bin/bash
path_dotfiles=~/dotfiles

#################################
#################################
# Aliases from the dotbot repo

# Use colors in coreutils utilities output
alias ls='ls --color=auto --group-directories-first'
alias grep='grep --color'

# ls aliases
alias la='ls -A'
alias l='ls -lah'

# Aliases to protect against overwriting
alias cp='cp -i'
alias mv='mv -i'

# git related aliases
alias gag='git exec ag'

# Update dotfiles
dfu() {
    (
        cd ~/.dotfiles && git pull --ff-only && ./install -q
    )
}

# Use pip without requiring virtualenv
syspip() {
    PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

syspip2() {
    PIP_REQUIRE_VIRTUALENV="" pip2 "$@"
}

syspip3() {
    PIP_REQUIRE_VIRTUALENV="" pip3 "$@"
}

# cd to git root directory
alias cdgr='cd "$(git root)"'

# Create a directory and cd into it
mcd() {
    mkdir "${1}" && cd "${1}"
}

# Jump to directory containing file
#jump() {
#    cd "$(dirname ${1})"
#}

# cd replacement for screen to track cwd (like tmux)
scr_cd()
{
    builtin cd $1
    screen -X chdir "$PWD"
}

if [[ -n $STY ]]; then
    alias cd=scr_cd
fi

# Go up [n] directories
up()
{
    local cdir="$(pwd)"
    if [[ "${1}" == "" ]]; then
        cdir="$(dirname "${cdir}")"
    elif ! [[ "${1}" =~ ^[0-9]+$ ]]; then
        echo "Error: argument must be a number"
    elif ! [[ "${1}" -gt "0" ]]; then
        echo "Error: argument must be positive"
    else
        for ((i=0; i<${1}; i++)); do
            local ncdir="$(dirname "${cdir}")"
            if [[ "${cdir}" == "${ncdir}" ]]; then
                break
            else
                cdir="${ncdir}"
            fi
        done
    fi
    cd "${cdir}"
}

# Execute a command in a specific directory
xin() {
    (
        cd "${1}" && shift && ${@}
    )
}

# Check if a file contains non-ascii characters
nonascii() {
    LC_ALL=C grep -n '[^[:print:][:space:]]' "${1}"
}

# Fetch pull request

fpr() {
    if ! git rev-parse --git-dir > /dev/null 2>&1; then
        echo "error: fpr must be executed from within a git repository"
        return 1
    fi
    (
        cdgr
        if [ "$#" -eq 2 ]; then
            local repo="${PWD##*/}"
            local user="${1}"
            local branch="${2}"
        elif [ "$#" -eq 3 ]; then
            local repo="${1}"
            local user="${2}"
            local branch="${3}"
        else
            echo "Usage: fpr [repo] username branch"
            return 1
        fi

        git fetch "git@github.com:${user}/${repo}" "${branch}:${user}/${branch}"
    )
}

# Serve current directory

serve() {
    ruby -run -e httpd . -p "${1:-8080}"
}

# Mirror a website
alias mirrorsite='wget -m -k -K -E -e robots=off'

# Mirror stdout to stderr, useful for seeing data going through a pipe
alias peek='tee >(cat 1>&2)'


#################################
#################################
# Mes aliases
# \cls to use cls command without alias (if the command exists)
#alias ls='ls -alh'
alias cd_cockpit='cd C:/Users/FebvreA/dev/docker/script'
alias c='clear' #ctrl L idem
alias q='exit'
alias ..='cd ..  && ls'
alias ...='cd ../..  && ls'
alias ....='cd ../../..  && ls'
alias g='grep'
alias G='grep -i'
alias pdf='xdg-open'
alias agi='sudo apt-get install'
alias agr='sudo apt-get remove'
alias agar='sudo apt-get autoremove'
alias agac='sudo apt-get autoclean'
alias agug='sudo apt-get upgrade'
alias agud='sudo apt-get update'
alias h='history'
alias hg='history | grep'
alias envp='source activate'
alias life_exp='source activate toto && cd ~/Documents/Projects/lifeExpectancyWiki/ && ipython'
alias bonjour='echo Bonjour ô mon maître.'
alias netw='sudo netstat -tupln'
alias alo='gvim $path_dotfiles/aliases'
alias bao='gvim $path_dotfiles/bash_commands'
alias pyo='gvim $path_dotfiles/python_commands'
alias vio='gvim $path_dotfiles/vim_commands'
alias ro='gvim  $path_dotfiles/r_commands'
alias alv='less $path_dotfiles/aliases'
alias bav='less $path_dotfiles/bash_commands'
alias pyv='less $path_dotfiles/python_commands'
alias viv='less $path_dotfiles/vim_commands'
alias rv='less  $path_dotfiles/r_commands'
alias scrab='cd ~/Documents/Projects/Scrabble && envp scrab'
alias fonction='typeset -F'
alias path='echo -e ${PATH//:/\\n}'
alias git_start='git init && git remote add settings https://github.com/Zibzob/main_settings.git'
alias git_pull='git pull settings master'
alias git_set_maj='git add .bash_aliases bash_command.sh .vimrc r_command.R python_command.py && git commit -m "maj settings" .bash_aliases bash_command.sh .vimrc r_command.R python_command.py && git push settings master'
#alias cdML='cd $(dirname $(locate evalAF.py)) && ls'
alias git_push_main='git add .bash_aliases .bashrc python_command.py bash_command.sh r_command.R .vimrc & git commit -a -m "Fichiers settings de base linux" & git push main_settings master'
alias pfr='d ~/Documents/CoursINSA/PFR'
alias po='poweroff'
alias cv='d ~/Documents/job/CV'
alias pfr_2048='d ~/Documents/CoursINSA/PFR && gvim -O jeu_2048.py play_2048.py play_2048_test.py pfr.py && envp pfr && vpython'
alias pfr_r='d ~/Documents/CoursINSA/PFR/Rapport/Rapport_theseTemplate'
alias pfr_redac='d ~/Documents/CoursINSA/PFR/Rapport/Rapport_theseTemplate && gvim -O main.tex MastersDoctoralThesis.cls Chapters/*.tex'
alias pfrold='d ~/Documents/CoursINSA/PFR && gvim pfr_old.py'
alias cdml='d ~/Documents/CoursINSA/ML/ML2/TP3_Selection'
alias cdGraph='d ~/Documents/CoursINSA/Optimisation/TP_Dijkstra'
alias cdinsa='d ~/Documents/CoursINSA'
alias ipy='envp toto && vpython'
alias nautML='nautilus $(dirname $(locate evalAF.py))'
alias noteML='cdML && envp toto && jupyter notebook'
alias jn='envp toto && jupyter notebook &'
alias p='cdinsa && grepPython'
#alias vpython='ipython3 --TerminalInteractiveShell.editing_mode=vi -pylab'
alias vpython='ipython3 -pylab'
alias rectype='source activate toto;python /home/aurelf/Documents/Projects/MISCELLANEOUS/typing_speed.py &;disown'

# Cree le repertoire et va dedans : function mkcd() { mkdir $1 && cd $1 }
function mkcd() { 
mkdir $1 && cd $1
}

# append to my alias file : function ala() { echo $1 >> $path_dotfiles/aliases }
function ala() { 
echo $1 >> $path_dotfiles/aliases
}

# append to my bash commands file : function baa() { echo $1 >> $path_dotfiles/bash_commands }
function baa() { 
echo $1 >> $path_dotfiles/bash_commands
}

# append to my python commands file : function pya() { echo $1 >> $path_dotfiles/python_commands }
function pya() { 
echo $1 >> $path_dotfiles/python_commands
}

# append to my vim commands file : function via() { echo $1 >> $path_dotfiles/vim_commands }
function via() { 
echo $1 >> $path_dotfiles/vim_commands
}

# append to my R commands file : function ra() { echo $1 >> $path_dotfiles/r_commands }
function ra() { 
echo $1 >> $path_dotfiles/r_commands
}

# grep in my alias file : function alg() { grep -i $1 $path_dotfiles/aliases }
function alg() { 
grep -i $1 $path_dotfiles/aliases
}

# grep in all alias : function ag() { alias | grep -i $1 }
function ag() { 
alias | grep -i $1 
}

# grep in my bash commands file : function bag() { grep -i $1 $path_dotfiles/bash_commands }
function bag() { 
grep -i $1 $path_dotfiles/bash_commands
}

# grep in my python commands file : function pyg() { grep -i $1 $path_dotfiles/python_commands }
function pyg() { 
grep -i $1 $path_dotfiles/python_commands
}

# grep in my bash commands file : function bag() { grep -i $1 $path_dotfiles/bash_commands }
function gall() { 
grep -i $1 $path_dotfiles/*
}

# grep in my gvim commands file : function vig() { grep -i $1 $path_dotfiles/vim_commands }
function vig() { 
grep -i $1 $path_dotfiles/vim_commands
}

# grep in my R commands file : function rg() { grep -i $1 $path_dotfiles/r_commands }
function rg() { 
grep -i $1 $path_dotfiles/r_commands
}

function d() { # change directory and ls
    if [[$1 == '']]
    then
        cd ~/ && ls
    else
        cd $1 && ls
    fi
}

# Search a regex through all python documents in children files : function grepPython() { grep -i $1 $(find -iname *.py) }
function grepPython() { 
grep -i $1 $(find -iname '*.py')
}

# Go to the first directory containing the looked up file : function goto() { cd $(dirname $(find -iname $1)) && ls }
function goto() { 
cd $(dirname $(find -iname '$1')) && ls
}

# Grep through all the available commands : function cmd() { compgen -A function -abck | grep $1 | sort | grep $1 } 
function cmd() {
    bash -c "compgen -A function -abck" | sort | grep $1
    apt list --installed | grep $1
    man -k $1
} 

# Grep through all available packages from apt-get : function sap() { apt-cache search . | grep $1 }
function sap() { 
apt-cache search . | grep $1
}

# Grep through all the installed programs : function sip() { apt list --installed | grep $1 }
function sip() { 
apt list --installed | grep $1
}

function create() {
    cd
    source activate toto
    python create.py $1
    cd /home/aurelf/Documents/Projects/$1
    git init
    git remote add origin git@github.com:Zibzob/$1.git
    touch README.md
    git add .
    git commit -m "Initial commit"
    git push -u origin master
    gvim .
}

function remove() {
    my_id=aurelf
    my_password=Basketball89!
    cd
    source activate toto
    python remove.py $1 $my_id $my_password
    cd /home/aurelf/Documents/Projects/$1
    rm -rf .git
}
